level-seed=coderyomc-p2-parity-7777
level-name=world
online-mode=false
server-port=28765
enable-status=false
spawn-protection=0
max-players=1
view-distance=6
simulation-distance=6
generate-structures=true
allow-nether=false
allow-end=false
